# File: roles/postgresql/tasks/packages.yml
---
# Must be installed before PostgreSQL
- name: 'Install locales-all in Debian'
  apt:
    pkg: 'locales-all'
    state: present
  when: ansible_distribution == 'Debian'
  retries: 3
  delay: 10
  until: apt_result|success
  register: apt_result
  tags:
    - packages

- name: 'Install PostgreSQL'
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: false
  with_items: "{{ packages_postgresql }}"
  retries: 3
  delay: 10
  until: apt_result|success
  register: apt_result
  tags:
    - packages
