# File: pre_install.yml
#
# Usage example:
# ansible-playbook -i inventory/example pre_install.yml --limit=srv01.example.com

---
- name: 'Raw install python-minimal'
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: 'apt-get install -y python-minimal python-apt'
      raw: test -e /usr/bin/python || apt-get install -y python-minimal python-apt
      register: apt_result
      changed_when: apt_result.stdout

    - name: 'apt-get install -y sudo'
      raw: test -e /usr/bin/sudo || apt-get install -y sudo
      register: apt_result
      changed_when: apt_result.stdout
