# File: roles/websites_common/tasks/users_groups_websites.yml
---
- name: 'Create directory {{ web_home_path }}'
  file:
    state: directory
    path: "{{ web_home_path }}"
    owner: 'root'
    group: 'root'
    mode: 0755

- name: 'Create group account for websites'
  group:
    state: present
    name: "{{ item.value.user }}"
  with_dict: "{{ all_websites }}"

- name: 'Create user account for websites'
  user:
    state: present
    name: "{{ item.value.user }}"
    group: "{{ item.value.user }}"
    home: "{{ web_home_path }}/{{ item.value.user }}"
    move_home: false
    comment: "{{ item.key }}"
  with_dict: "{{ all_websites }}"

- name: 'Create user directory www for websites'
  file:
    state: directory
    path: "{{ web_home_path }}/{{ item.value.user }}/www"
    owner: "{{ item.value.user }}"
    group: 'www-data'
    mode: 0750
  with_dict: "{{ all_websites }}"
