# File: roles/mysql/tasks/mysql.yml
---
- name: 'Create Application Database'
  mysql_db:
    state: present
    name: "{{ item.value.user[:16] }}"
  when: item.value.db_type == 'mysql'
    and item.value.mysql.password is defined
  with_dict: "{{ all_websites }}"
  tags:
    - mysql

- name: 'Create Application DB User'
  mysql_user:
    state: present
    name: "{{ item.value.user[:16] }}"
    password: "{{ item.value.mysql.password }}"
    priv: "{{ item.value.user[:16] }}.*:ALL"
    host: '%'
  when: item.value.db_type == 'mysql'
    and item.value.mysql.password is defined
  with_dict: "{{ all_websites }}"
  register: reg_mysql
  tags:
    - mysql

  # TODO: Maybe module 'get_url' would be better choose
- name: 'Upload DB backup'
  become: true
  become_user: "{{ item.item.value.user }}"
  copy:
    src: "{{ backup_path }}/{{ item.item.key }}.sql.gz"
    dest: '/tmp/'
  when: item.changed and item.item.value.mysql.backup_path is defined
  with_items: "{{ reg_mysql.results }}"


- name: 'Import DB'
  mysql_db:
    state: import
    name: "{{ item.item.value.user[:16] }}"
    target: "/tmp/{{ item.item.key }}.sql.gz"
  when: item.changed and item.item.value.mysql.backup_path is defined
  with_items: "{{ reg_mysql.results }}"
  tags:
    - mysql
